name: Sigrid PR feedback
on:
  pull_request:

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@main
        with:
          customer: kiesraad
          system: abacus
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_TOKEN }}"
      - name: "Sigrid PR feedback"
        uses: mshick/add-pr-comment@v2
        if: always()
        with:
          message-id: sigrid
          message-path: sigrid-ci-output/feedback.md
